name: curryware-firebase-auth Build
on: [push]
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Source
        uses: actions/checkout@v4

      - name: Install-Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test with Pytest
        env:
          FIREBASE_ADMIN_SDK_JSON: ${{ secrets.FIREBASE_ADMIN_SDK_JSON }}
          FIREBASE_DATABASE_NAME: ${{ secrets.FIREBASE_DATABASE_NAME }}
        run: |
          pip install pytest pytest-cov
          pytest tests/

      - name: Check imported libraries are secure and compliant
        id: datadog-software-composition-analysis
        uses: DataDog/datadog-sca-github-action@main
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_env: ci
          dd_service: curryware-firebase-auth
          dd_site: datadoghq.com

      # https://github.com/docker/build-push-action/?tab=readme-ov-file#path-context
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          # Don't forget to set the IMAGE_NAME environment variable.
          tags: scotcurry4/curryware-firebase-auth:${{ github.run_number}}
          labels: |
            org.opencontainers.image.source=github.com/scotcurry/curryware-firebase-auth
            org.opencontainers.image.revision=${{ github.sha }}
            tags.datadoghq.com/env=prod
            tags.datadoghq.com/version=${{ github.run_number }}
            tags.datadoghq.com/service=curryware-firebase-auth
